package entities;
// Generated Dec 10, 2021, 7:52:51 PM by Hibernate Tools 5.5.7.Final

import java.util.Date;

/**
 * Companies generated by hbm2java
 */
public class Companies implements java.io.Serializable {

	private int companyId;
	private String name;
	private String address;
	private int noOfEmployee;
	private Date regYear;
	private String regCountry;

	public Companies() {
	}

	public Companies(int companyId, String name, String address, int noOfEmployee, Date regYear, String regCountry) {
		this.companyId = companyId;
		this.name = name;
		this.address = address;
		this.noOfEmployee = noOfEmployee;
		this.regYear = regYear;
		this.regCountry = regCountry;
	}

	public int getCompanyId() {
		return this.companyId;
	}

	public void setCompanyId(int companyId) {
		this.companyId = companyId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public int getNoOfEmployee() {
		return this.noOfEmployee;
	}

	public void setNoOfEmployee(int noOfEmployee) {
		this.noOfEmployee = noOfEmployee;
	}

	public Date getRegYear() {
		return this.regYear;
	}

	public void setRegYear(Date regYear) {
		this.regYear = regYear;
	}

	public String getRegCountry() {
		return this.regCountry;
	}

	public void setRegCountry(String regCountry) {
		this.regCountry = regCountry;
	}

}
