package entities;
// Generated Dec 10, 2021, 7:52:51 PM by Hibernate Tools 5.5.7.Final

import java.util.Date;

/**
 * Supervisor generated by hbm2java
 */
public class Supervisor implements java.io.Serializable {

	private Integer supervisorId;
	private String studentId;
	private String CName;
	private String CAddress;
	private String supName;
	private String title;
	private String email;
	private String number;
	private Date start;
	private Date end;
	private int hours;
	private String task;
	private String learn;
	private String specialization;

	public Supervisor() {
	}

	public Supervisor(String studentId, String CName, String CAddress, String supName, String title, String email,
			String number, Date start, Date end, int hours, String task, String learn, String specialization) {
		this.studentId = studentId;
		this.CName = CName;
		this.CAddress = CAddress;
		this.supName = supName;
		this.title = title;
		this.email = email;
		this.number = number;
		this.start = start;
		this.end = end;
		this.hours = hours;
		this.task = task;
		this.learn = learn;
		this.specialization = specialization;
	}

	public Integer getSupervisorId() {
		return this.supervisorId;
	}

	public void setSupervisorId(Integer supervisorId) {
		this.supervisorId = supervisorId;
	}

	public String getStudentId() {
		return this.studentId;
	}

	public void setStudentId(String studentId) {
		this.studentId = studentId;
	}

	public String getCName() {
		return this.CName;
	}

	public void setCName(String CName) {
		this.CName = CName;
	}

	public String getCAddress() {
		return this.CAddress;
	}

	public void setCAddress(String CAddress) {
		this.CAddress = CAddress;
	}

	public String getSupName() {
		return this.supName;
	}

	public void setSupName(String supName) {
		this.supName = supName;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getNumber() {
		return this.number;
	}

	public void setNumber(String number) {
		this.number = number;
	}

	public Date getStart() {
		return this.start;
	}

	public void setStart(Date start) {
		this.start = start;
	}

	public Date getEnd() {
		return this.end;
	}

	public void setEnd(Date end) {
		this.end = end;
	}

	public int getHours() {
		return this.hours;
	}

	public void setHours(int hours) {
		this.hours = hours;
	}

	public String getTask() {
		return this.task;
	}

	public void setTask(String task) {
		this.task = task;
	}

	public String getLearn() {
		return this.learn;
	}

	public void setLearn(String learn) {
		this.learn = learn;
	}

	public String getSpecialization() {
		return this.specialization;
	}

	public void setSpecialization(String specialization) {
		this.specialization = specialization;
	}

}
